### ISSUE TITLE
Difference from existing Game Time Starter Kit

### ISSUE THREAD

**Issue by stevekinney** [turingschool-examples/game-time-starter-kit-FEm1#2]
@robbiejaeger Out of curiosity…

1. What is going to be the difference between this starter kit and the existing one? 
2. Would it make sense to update the existing one with whatever changes instead of having the confusion of two?

**Comment by robbiejaeger** [comment]
@stevekinney 

The main difference is to be very explicit in the structure of game time and how to use webpack (explained in the documentation). My thoughts were that if mod4 BE wants to use the existing game time starter kit that maybe instructors don't want the documentation so that students intentionally need to figure out more about using webpack.

That being said, if that's not something instructors are concerned about (especially if mod4 BE isn't doing game time in the future), then I think it would be better to just modify the existing repo.

**Comment by nfosterky** [comment]
I agree with @robbiejaeger
